version: '3'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankcards_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./logs:/workspace/logs



volumes:
  pgdata:

